### Global gh-pages pre-amble
safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


### The following properties will change on a project-by-project basis

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
baseurl: /spring-data

# Name of the project for display in places like page titles
name: Spring Data

# ID of the project in the metadata API at springframework.io (if this is not a
# valid project ID the javascript widgets in the home page will not work)
project: spring-data

# Project github URL
github_repo_url: http://github.com/spring-projects/spring-data

# Project forum URL
forum: http://forum.stage.springsource.org/forum/spring-projects/data


### The following properties are constant for most projects

main_site_url: http://springframework.io
projects_site_url: http://projects.springframework.io
forum_url: http://forum.springframework.io


### For testing only
#sample: true
